spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mwmdbfinal?useSSL=false
    username: root
    password: 147*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false 